export const classNames = {
    SafariUI: 'SafariUI',
    SafariUIDisabled: 'SafariUI-disabled',
    SafariUIButton: 'SafariUI-btn',
    SafariUIButtonText: 'SafariUI-btn-text',
    SafariUIButtonOutlined: 'SafariUI-btn-outlined',
    SafariUILoader: 'SafariUI-loader',
    SafariUILoaderEllipsis: 'SafariUI-loader-ellipsis',
    SafariUILoaderEllipsisDot: 'SafariUI-loader-ellipsis-dot',
    SafariUILoaderEllipsisRolling: 'SafariUI-loader-ellipsisRolling',
    SafariUILoaderSpinner: 'SafariUI-loader-spinner',
    SafariUILoaderSpinnerDot: 'SafariUI-loader-spinner-dot',
    SafariUILoaderRoller: 'SafariUI-loader-roller',
    SafariUILoaderRollerDot: 'SafariUI-loader-roller-dot',
    SafariUILoaderRollerTrailing: 'SafariUI-loader-rollerTrailing',
    SafariUILoaderRing: 'SafariUI-loader-ring',
    SafariUILoaderRingTrail: 'SafariUI-loader-ring-trail',
};
